Repository erxes/erxes-api, pull requests merged in 2020-10, with the labels that each got.

#862 Webhooks
  package.json
  src/__tests__/integrationMutations.test.ts
  src/__tests__/webhookDb.test.ts
  src/__tests__/webhookMutations.test.ts
  src/__tests__/webhookQueries.test.ts
  src/data/constants.ts
  src/data/logUtils.ts
  src/data/resolvers/mutations/conversations.ts
  src/data/resolvers/mutations/engages.ts
  src/data/resolvers/mutations/index.ts
  src/data/resolvers/mutations/integrations.ts
  src/data/resolvers/mutations/webhooks.ts
  src/data/resolvers/mutations/widgets.ts
  src/data/resolvers/queries/configs.ts
  src/data/resolvers/queries/index.ts
  src/data/resolvers/queries/webhooks.ts
  src/data/schema/index.ts
  src/data/schema/integration.ts
  src/data/schema/webhook.ts
  src/data/utils.ts
  src/db/factories.ts
  src/db/models/Conversations.ts
  src/db/models/Webhook.ts
  src/db/models/definitions/constants.ts
  src/db/models/definitions/integrations.ts
  src/db/models/definitions/webhook.ts
  src/db/models/index.ts
  src/index.ts
  src/middlewares/webhookMiddleware.ts
  yarn.lock
Labels: feature

#872 Update conversations.ts
  src/cronJobs/conversations.ts
Labels: hacktoberfest-accepted

#870 fix(integration): now allowing multiple messenger for one brand
  src/__tests__/integrationDb.test.ts
  src/__tests__/integrationMutations.test.ts
  src/data/utils.ts
  src/db/models/Integrations.ts
  src/index.ts
Labels: enhancement, hacktoberfest-accepted

#877 Auto completion
  src/data/modules/coc/utils.ts
  src/data/schema/company.ts
  src/data/schema/customer.ts
Labels: hacktoberfest-accepted
